apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    isDefault: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: ""
      spanBar:
        type: "Tag"
        tag: "http.request.method"
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
